


<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/homeIndexPic.js">

/* ==== slider nameSpace ==== */
</script>



<div id="center">

	<div id="slider">

		<div class="slide">

			<img class="diapo" src="<?php echo Yii::app()->request->baseUrl ?>/images/homeCake1.jpg" alt="">

			<div class="text">

				  <span class="title">Purple Love</span>

				  Purple Love , when you are falling love with someone, world becomes purple. 

				  Did you have experience such feeling with purple love ?

			</div>

		</div>

		<div class="slide">

			<img class="diapo" src="<?php echo Yii::app()->request->baseUrl ?>/images/homeCake2.jpg" alt="">

			<div class="text">

				<span class="title">Chiristmas</span>

				Merry Christmas , lonly Christmas..

				originated in the prototype model, that creates its own variational

				principles, as oriented by the first local generation of terminable androids.

			</div>

		</div>

		<div class="slide">

			<img class="diapo" src="<?php echo Yii::app()->request->baseUrl ?>/images/homeCake3.jpg" alt="">

			<div class="text">

				  <span class="title">Fruit Passion</span>

				  So much Fruit, so much passion! Summer!

				  reduced to a half the original as planned, and indeed they show an

				  evolutionary advantage in the process of fixing self-generated instructions.

				  Plus, they are beautiful.

			</div>

		</div>

		<div class="slide">

			<img class="diapo" src="<?php echo Yii::app()->request->baseUrl ?>/images/homeCake5.jpg" alt="">

			<div class="text">

				<span class="title">Coffee Cake</span>

				Coffee and cake are born a couple!

				close-alikes to us. However, they will not be audible, at least not in my

				life span. We resolved the low freq vibration a superior solution for our

				communicational goals ...

			</div>

		</div>

		<div class="slide">

			<img class="diapo" src="<?php echo Yii::app()->request->baseUrl ?>/images/homeCake4.jpg" alt="">

			<div class="text">

				  <span class="title">Green Childhood</span>

				  Our childhood are all Green with Happyness!

				  this is the best model so far. I shall have to bear with the inconveniences.

				  They seem to establish a parallel communication through that carbon coat and

				  I find myself unable to decodify the signal into anything meaningful.

			</div>

		</div>

		<div class="slide">

			<img class="diapo" src="<?php echo Yii::app()->request->baseUrl ?>/images/homeCake6.jpg" alt="">

			<div class="text">

				  <span class="title">Black Cream</span>

				  Today a set of vibration came up from the zero level;  we expect to launch

				  the transitional program in no longer than five basetime units. Psykesoma?				  galore and we'll betray our very nature into infinite, unending 2D surfaces.

				  We do need that vibration, and we will conquer its source.

			</div>

		</div>

		<div class="slide">

			<img class="diapo" src="<?php echo Yii::app()->request->baseUrl ?>/images/homeCake7.jpg" alt="">

			<div class="text">

				  <span class="title">Hey Chocolate</span>

				  To keep my sanity I wear the tactile sensors all the time. They translate

				  beautifully; I can even see distances while still on Psykesoma. This was

				  quite a discovery. We have grown more adaptable than expected.

			</div>

		</div>

		<div class="slide">

			<img class="diapo" src="<?php echo Yii::app()->request->baseUrl ?>/images/homeCake8.jpg" alt="">

			<div class="text">

				  <span class="title">Tea Cookie</span>

				  Yewoona had to travel farther and longer than I did. Her base orbiter was

				  set to keep a complex combinational path that made it uneasy to match our

				  circuits. But her nature showed stronger than programmed.

			</div>

		</div>

		<div class="slide">

			<img class="diapo" src="<?php echo Yii::app()->request->baseUrl ?>/images/homeCake9.jpg" alt="">

			<div class="text">

				  <span class="title">House Inside</span>

				  Keep feeding them. We will never be this lucky again; an autogenerated

				  species adapted to serve all our needs!

			</div>

		</div>

		<div class="slide">

			<img class="diapo" src="<?php echo Yii::app()->request->baseUrl ?>/images/homeCake10.png" alt="">

			<div class="text">

				  <span class="title">House Outsider</span>

				  "Blood is dark red, iron dark blue, this tale is blissful and so are you". I

				  should get to the hotel at soonest. The agency guy must be there already,

				  with some luck we'll have some nice dinner on him. How's that?

			</div>

		</div>

	</div>

</div>



<script type="text/javascript">

/* ==== start script ==== */

slider.init();

</script>



